# Generated by Django 5.0.6 on 2026-03-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='photo',
        ),
        migrations.AddField(
            model_name='authority',
            name='photo1',
            field=models.FileField(blank=True, null=True, upload_to='authority_photo'),
        ),
        migrations.AddField(
            model_name='authority',
            name='photo2',
            field=models.FileField(blank=True, null=True, upload_to='authority_photo'),
        ),
        migrations.AddField(
            model_name='authority',
            name='photo3',
            field=models.FileField(blank=True, null=True, upload_to='authority_photo'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='photo1',
            field=models.FileField(blank=True, null=True, upload_to='familymember_photo'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='photo2',
            field=models.FileField(blank=True, null=True, upload_to='familymember_photo'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='photo3',
            field=models.FileField(blank=True, null=True, upload_to='familymember_photo'),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo1',
            field=models.FileField(blank=True, null=True, upload_to='resident_photo'),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo2',
            field=models.FileField(blank=True, null=True, upload_to='resident_photo'),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo3',
            field=models.FileField(blank=True, null=True, upload_to='resident_photo'),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo1',
            field=models.FileField(blank=True, null=True, upload_to='worker_photo'),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo2',
            field=models.FileField(blank=True, null=True, upload_to='worker_photo'),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo3',
            field=models.FileField(blank=True, null=True, upload_to='worker_photo'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='worker_id'),
        ),
    ]
