# Generated by Django 5.0.6 on 2026-03-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_resident_photo_authority_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='authority',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='photo3',
        ),
    ]
