# Generated by Django 5.0.6 on 2026-03-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_authority_photo2_remove_authority_photo3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='straydogalert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stray_dog_alerts/'),
        ),
    ]
