# Generated by Django 5.0.6 on 2026-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_straydogalert_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
    ]
